## This workflow runs any time code is pushed to a branch.
## By doing so, Branches always have up-to-date results in Workbench.
name: Scan-Git with Script
on: workflow_dispatch
      
jobs:
  workbench_git_scan:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}
      
    steps:
      - name: Checkout Workbench Agent
        uses: actions/checkout@v4
        with: 
          repository: tomgonzo/workbench-agent
          path: fossid-tools

      - name: Install Workbench Agent
        run: pip install ./fossid-tools

      - name: Pull from Git and Scan
        run: |
          workbench-agent scan-git \
            --project-name $GITHUB_REPOSITORY \
            --scan-name ScanGit-Script-$GITHUB_REF \
            --git-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
            --git-branch $GITHUB_REF_NAME \
            --git-depth 1 \
            --run-dependency-analysis \
            --autoid-file-licenses \
            --autoid-file-copyrights \
            --id-reuse \
            --id-reuse-type project \
            --id-reuse-source $GITHUB_REPOSITORY \
            --show-scan-metrics

      - name: Show Scan Results
        run: |
          workbench-agent show-results \
            --project-name $GITHUB_REPOSITORY \
            --scan-name ScanGit-Script-$GITHUB_REF \
            --show-components \
            --show-dependencies \
            --show-licenses \
            --show-policy-warnings \
            --show-vulnerabilities
