## This workflow runs any time code is pushed to a branch.
## By doing so, Branches always have up-to-date results in Workbench.
name: Update Branch Scan using Zip Upload
on: push
      
jobs:
  fossid_scan:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}

    steps:
      - name: Checkout Workbench Agent
        uses: actions/checkout@v4
        with: 
          repository: tomgonzo/workbench-agent
          path: fossid-tools

      - name: Install Workbench Agent
        run: pip install ./fossid-tools

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Upload Prep; Zip Code
        run: |
          zip -r $GITHUB_WORKSPACE/code.zip . -x \
          '*.tmp' '*.temp' '*.bak' \
          '*.cache' '*.db' '*.idx' \
          '*.log' '*.txt' '*.event' \
          '*.sample' '*.demo' '*.example' \
          '*.sql' '*.hprof' '*.dmp' \
          '.gitignore' '.dockerignore' \
          '.git/*' '.github/*'

      - name: Scan by Uploading a Zip
        run: |
          workbench-agent scan-git \
            --project-name $GITHUB_REPOSITORY \
            --scan-name ZipScan-$GITHUB_REF \
            --path $GITHUB_WORKSPACE/code.zip \
            --run-dependency-analysis \
            --autoid-file-licenses \
            --autoid-file-copyrights \
            --id-reuse \
            --id-reuse-type project \
            --id-reuse-source $GITHUB_REPOSITORY \
            --show-scan-metrics

      - name: Show Scan Results
        run: |
          workbench-agent show-results \
            --project-name $GITHUB_REPOSITORY \
            --scan-name ZipScan-$GITHUB_REF \
            --show-components \
            --show-dependencies \
            --show-licenses \
            --show-policy-warnings \
            --show-vulnerabilities